#!/usr/bin/env python3
"""Render the documentation diagrams from Graphviz sources.

Sources live in ``book/diagrams/*.dot``; rendered SVGs are written to
``book/src/assets/diagrams/*.svg`` and committed alongside them, the same way
``website/assets/quickstart-graph.dot`` and its SVG are handled. Committing the
output keeps Graphviz out of the docs CI job.

Run after editing any .dot file:

    scripts/render_diagrams.py

The rendered SVG is post-processed so it behaves in a documentation page:

  * the opaque background polygon Graphviz emits is dropped, so the diagram sits
    on whatever surface the page gives it
  * the fixed ``width``/``height`` attributes are dropped and the ``viewBox`` is
    kept, so the image scales down on narrow screens instead of overflowing
  * the generator comment and DOCTYPE are stripped to keep diffs small

Diagrams are styled for a light plate (see ``.diagram`` in book/src/custom.css),
which is what makes them legible on every mdBook theme including navy.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOT_DIR = REPO_ROOT / "book" / "diagrams"
SVG_DIR = REPO_ROOT / "book" / "src" / "assets" / "diagrams"

DOCTYPE = re.compile(r"<!DOCTYPE[^>]*>\s*", re.I)
GENERATED_COMMENT = re.compile(r"<!--.*?-->\s*", re.S)
XML_DECL = re.compile(r"<\?xml[^>]*\?>\s*")
SVG_OPEN = re.compile(r"<svg\b([^>]*)>", re.I)
SIZE_ATTR = re.compile(r'\s(?:width|height)="[^"]*"', re.I)
# Graphviz emits the canvas fill as the first polygon in the root graph group.
BACKGROUND_POLYGON = re.compile(
    r'<polygon fill="(?:#ffffff|white)"[^/]*?/>\s*', re.I
)


def render(dot_path: Path) -> str:
    result = subprocess.run(
        ["dot", "-Tsvg", str(dot_path)],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"dot failed for {dot_path.name}:\n{result.stderr.strip()}")
    return result.stdout


def clean(svg: str) -> str:
    svg = XML_DECL.sub("", svg)
    svg = DOCTYPE.sub("", svg)
    # Graphviz emits a "Generated by" and a "Title:" comment ahead of <svg>.
    while (match := GENERATED_COMMENT.match(svg)) is not None:
        svg = svg[match.end():]
    svg = BACKGROUND_POLYGON.sub("", svg, count=1)

    def strip_size(match: re.Match[str]) -> str:
        return "<svg" + SIZE_ATTR.sub("", match.group(1)) + ">"

    svg = SVG_OPEN.sub(strip_size, svg, count=1)
    return svg.strip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dot-dir", type=Path, default=DOT_DIR, help="directory of .dot sources"
    )
    parser.add_argument(
        "--svg-dir", type=Path, default=SVG_DIR, help="directory to write .svg into"
    )
    args = parser.parse_args()

    if shutil.which("dot") is None:
        print(
            "error: graphviz not found. Install it with `brew install graphviz` "
            "or `apt-get install graphviz`.",
            file=sys.stderr,
        )
        return 1

    sources = sorted(args.dot_dir.rglob("*.dot"))
    if not sources:
        print(f"error: no .dot files under {args.dot_dir}", file=sys.stderr)
        return 1

    args.svg_dir.mkdir(parents=True, exist_ok=True)
    written = unchanged = 0

    for source in sources:
        target = args.svg_dir / (source.stem + ".svg")
        svg = clean(render(source))
        if target.exists() and target.read_text(encoding="utf-8") == svg:
            unchanged += 1
            continue
        target.write_text(svg, encoding="utf-8")
        written += 1
        print(f"  rendered {source.stem}.svg")

    # Flag SVGs whose .dot source has been deleted or renamed.
    expected = {source.stem + ".svg" for source in sources}
    orphans = sorted(p.name for p in args.svg_dir.glob("*.svg") if p.name not in expected)
    for orphan in orphans:
        print(f"  warning: {orphan} has no .dot source", file=sys.stderr)

    print(f"render_diagrams: {written} written, {unchanged} unchanged, {len(sources)} total")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
